version: "3.9"
services:

  api-py:
    build:
      context: ./api-vise-py      # <- carpeta del proyecto Python
      dockerfile: Dockerfile
    container_name: api-vise-py
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3