name: Build container and run VISE API testing

on:
  workflow_dispatch:
    inputs:
      PORT:
        description: "Host port to expose the API (container listens on 8000)"
        required: true
        default: "8000"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t vise-api:latest .

      - name: Run container
        run: |
          docker run -d \
            --name vise-api \
            -p ${{ inputs.PORT }}:8000 \
            vise-api:latest

      - name: Wait for /health
        run: |
          for i in {1..30}; do
            if curl -fsS "http://localhost:${{ inputs.PORT }}/health" >/dev/null; then
              echo "API is healthy"; exit 0
            fi
            sleep 1
          done
          echo "API did not become healthy in time" >&2
          docker logs vise-api || true
          exit 1

      - name: Install Hurl
        uses: gacts/install-hurl@v1

      - name: Test API with Hurl
        run: hurl --variable host=http://localhost:${{ inputs.PORT }} --error-format long --test session.hurl

      - name: Show logs on failure
        if: failure()
        run: docker logs vise-api || true

      - name: Stop container
        if: always()
        run: docker rm -f vise-api
